CREATE TABLE USER_INFO(
    USER_NO NUMBER CONSTRAINT USER_NO_PK PRIMARY KEY,
    USER_NAME VARCHAR2(10),
    USER_ID VARCHAR2(10) CONSTRAINT USER_ID_NN NOT NULL,
    USER_PWD VARCHAR2(20) CONSTRAINT USER_PWD_NN NOT NULL,
    EMAIL VARCHAR2(20),
    PHONE VARCHAR2(20),
    ADDRESS VARCHAR2(20),
    SHOES_SIZE NUMBER,
    POINT NUMBER,
    MGR CHAR(1),
    BANK_NAME VARCHAR2(5),
    ACCOUNT_NO VARCHAR2(20),
    CONSTRAINT USER_ID_UK UNIQUE(USER_ID)
);

COMMENT ON COLUMN USER_INFO.USER_NO IS '번호';
COMMENT ON COLUMN USER_INFO.USER_NAME IS '이름';
COMMENT ON COLUMN USER_INFO.USER_ID IS '아이디';
COMMENT ON COLUMN USER_INFO.USER_PWD IS '비밀번호';
COMMENT ON COLUMN USER_INFO.EMAIL IS '이메일';
COMMENT ON COLUMN USER_INFO.PHONE IS '전화번호';
COMMENT ON COLUMN USER_INFO.ADDRESS IS '주소';
COMMENT ON COLUMN USER_INFO.SHOES_SIZE IS '신발사이즈';
COMMENT ON COLUMN USER_INFO.POINT IS '적립포인트';
COMMENT ON COLUMN USER_INFO.MGR IS '관리자유무';
COMMENT ON COLUMN USER_INFO.BANK_NAME IS '은행명';
COMMENT ON COLUMN USER_INFO.ACCOUNT_NO IS '계좌번호';

CREATE TABLE ITEM(
    ITEM_NO NUMBER CONSTRAINT ITEM_NO_PK PRIMARY KEY,
    ITEM_NAME VARCHAR2(10) CONSTRAINT ITEM_NAME_NN NOT NULL,
    BRAND VARCHAR2(10) CONSTRAINT ITEM_BRAND_NN NOT NULL,
    PRICE NUMBER CONSTRAINT ITEM_PRICE_NN NOT NULL,
    REG_DATE DATE CONSTRAINT ITEM_REG_DATE_NN NOT NULL,
    DROP_DATE DATE CONSTRAINT ITEM_DROP_DATE_NN NOT NULL,
    SHOES_SIZE NUMBER CONSTRAINT ITEM_SHOES_SIZE_NN NOT NULL,
    CONSTRAINT ITEM_NAME_UK UNIQUE(ITEM_NAME)
);

COMMENT ON COLUMN ITEM.ITEM_NO IS '번호';
COMMENT ON COLUMN ITEM.ITEM_NAME IS '이름';
COMMENT ON COLUMN ITEM.BRAND IS '브랜드';
COMMENT ON COLUMN ITEM.PRICE IS '가격';
COMMENT ON COLUMN ITEM.REG_DATE IS '등록일자';
COMMENT ON COLUMN ITEM.DROP_DATE IS '발매일자';
COMMENT ON COLUMN ITEM.SHOES_SIZE IS '신발사이즈';

CREATE TABLE ITEM_REG_STA(
    ITEM_REG_STA_NO NUMBER CONSTRAINT ITEM_REG_STA_NO_PK PRIMARY KEY,
    USER_NO NUMBER CONSTRAINT ITEM_REG_STA_USER_NO_FK REFERENCES USER_INFO(USER_NO),
    USER_ID VARCHAR2(10) CONSTRAINT ITEM_REG_STA_USER_ID_FK REFERENCES USER_INFO(USER_ID),
    ITEM_NO NUMBER CONSTRAINT ITEM_REG_STA_ITEM_NO_FK REFERENCES ITEM(ITEM_NO),
    SHOES_SIZE NUMBER CONSTRAINT ITEM_REG_STA_SHOES_SIZE_NN NOT NULL,
    REG_DATE DATE CONSTRAINT ITEM_REG_STA_REG_DATE_NN NOT NULL,
    PRICE NUMBER CONSTRAINT ITEM_REG_STA_PRICE_NN NOT NULL
);

COMMENT ON COLUMN ITEM_REG_STA.ITEM_REG_STA_NO IS '번호';
COMMENT ON COLUMN ITEM_REG_STA.USER_NO IS '사용자번호';
COMMENT ON COLUMN ITEM_REG_STA.USER_ID IS '사용자아이디';
COMMENT ON COLUMN ITEM_REG_STA.ITEM_NO IS '상품번호';
COMMENT ON COLUMN ITEM_REG_STA.SHOES_SIZE IS '신발사이즈';
COMMENT ON COLUMN ITEM_REG_STA.REG_DATE IS '등록일자';
COMMENT ON COLUMN ITEM_REG_STA.PRICE IS '가격';

CREATE TABLE TEXT_LIST(
    TEXT_LIST_NO NUMBER CONSTRAINT TEXT_LIST_NO_PK PRIMARY KEY,
    USER_NO NUMBER CONSTRAINT TEXT_LIST_USER_NO_FK REFERENCES USER_INFO(USER_NO),
    TITLE VARCHAR2(20) CONSTRAINT TEXT_LIST_TITLE_NN NOT NULL,
    CONTENT VARCHAR2(100),
    REG_DATE DATE CONSTRAINT TEXT_LIST_REG_DATE_NN NOT NULL,
    CATEGORY VARCHAR2(10) CONSTRAINT TEXT_LIST_CATEGORY_NN NOT NULL,
    VIEWS NUMBER DEFAULT 0,
    HEART CHAR(1) DEFAULT 'N'
);

COMMENT ON COLUMN TEXT_LIST.TEXT_LIST_NO IS '번호';
COMMENT ON COLUMN TEXT_LIST.USER_NO IS '사용자번호';
COMMENT ON COLUMN TEXT_LIST.TITLE IS '제목';
COMMENT ON COLUMN TEXT_LIST.CONTENT IS '내용';
COMMENT ON COLUMN TEXT_LIST.REG_DATE IS '등록일자';
COMMENT ON COLUMN TEXT_LIST.CATEGORY IS '카테고리';
COMMENT ON COLUMN TEXT_LIST.VIEWS IS '조회수';
COMMENT ON COLUMN TEXT_LIST.HEART IS '좋아요';

CREATE TABLE WISH_LIST(
    WISH_LIST_NO NUMBER CONSTRAINT WISH_LIST_NO_PK PRIMARY KEY,
    USER_NO NUMBER CONSTRAINT WISH_LIST_USER_NO_FK REFERENCES USER_INFO(USER_NO),
    ITEM_NO NUMBER CONSTRAINT WISH_LIST_ITEM_NO_FK REFERENCES ITEM(ITEM_NO)
);

COMMENT ON COLUMN WISH_LIST.WISH_LIST_NO IS '번호';
COMMENT ON COLUMN WISH_LIST.USER_NO IS '사용자번호';
COMMENT ON COLUMN WISH_LIST.ITEM_NO IS '상품번호';

CREATE TABLE COMMENTS(
    COMMENTS_NO NUMBER CONSTRAINT COMMENTS_NO_PK PRIMARY KEY,
    REPLY_NO NUMBER CONSTRAINT COMMENTS_REPLY_NO_NN NOT NULL,
    COMMENTS_LEVEL NUMBER CONSTRAINT COMMENTS_LEVEL_NN NOT NULL,
    COMMENTS_SEQ NUMBER CONSTRAINT COMMENTS_SEQ_NN NOT NULL,
    CONSTRAINT COMMENTS_REPLY_NO_UK UNIQUE(REPLY_NO),
    CONSTRAINT COMMENTS_LEVEL_UK UNIQUE(COMMENTS_LEVEL),
    CONSTRAINT COMMENTS_SEQ_UK UNIQUE(COMMENTS_SEQ)
);

COMMENT ON COLUMN COMMENTS.COMMENTS_NO IS '번호';
COMMENT ON COLUMN COMMENTS.REPLY_NO IS '대댓글번호';
COMMENT ON COLUMN COMMENTS.COMMENTS_LEVEL IS '댓글단계';
COMMENT ON COLUMN COMMENTS.COMMENTS_SEQ IS '댓글순번';

CREATE TABLE ORDERS(
    ORDERS_NO NUMBER CONSTRAINT ORDERS_NO_PK PRIMARY KEY,
    USER_NO NUMBER CONSTRAINT ORDERS_USER_NO_FK REFERENCES USER_INFO(USER_NO),
    ITEM_NO NUMBER CONSTRAINT ORDERS_ITEM_NO_FK REFERENCES ITEM(ITEM_NO),
    USER_ID VARCHAR2(10) CONSTRAINT ORDERS_USER_ID_FK REFERENCES USER_INFO(USER_ID),
    PUR_DATE DATE CONSTRAINT ORDERS_PUR_DATE_NN NOT NULL,
    COUNT NUMBER DEFAULT 0,
    PROGRESS VARCHAR2(10) CONSTRAINT ORDERS_PROGRESS_NN NOT NULL,
    PRICE NUMBER CONSTRAINT ORDERS_PRICE_NN NOT NULL,
    ADDRESS VARCHAR2(20) CONSTRAINT ORDERS_ADDRESS_NN NOT NULL,
    SHOES_SIZE NUMBER CONSTRAINT ORDERS_SHOES_SIZE_NN NOT NULL,
    PHONE VARCHAR2(20) CONSTRAINT ORDERS_PHONE_NN NOT NULL,
    DEL_FEE NUMBER CONSTRAINT ORDERS_DEL_FEE_NN NOT NULL,
    PAYMENT VARCHAR2(10) CONSTRAINT ORDERS_PAYMENT_NN NOT NULL
);

COMMENT ON COLUMN ORDERS.ORDERS_NO IS '번호';
COMMENT ON COLUMN ORDERS.USER_NO IS '사용자번호';
COMMENT ON COLUMN ORDERS.ITEM_NO IS '상품번호';
COMMENT ON COLUMN ORDERS.USER_ID IS '사용자아이디';
COMMENT ON COLUMN ORDERS.PUR_DATE IS '구매일자';
COMMENT ON COLUMN ORDERS.COUNT IS '개수';
COMMENT ON COLUMN ORDERS.PROGRESS IS '진행상태';
COMMENT ON COLUMN ORDERS.PRICE IS '가격';
COMMENT ON COLUMN ORDERS.ADDRESS IS '주소';
COMMENT ON COLUMN ORDERS.SHOES_SIZE IS '신발사이즈';
COMMENT ON COLUMN ORDERS.PHONE IS '전화번호';
COMMENT ON COLUMN ORDERS.DEL_FEE IS '배송비';
COMMENT ON COLUMN ORDERS.PAYMENT IS '결제수단';

CREATE TABLE POINTS(
    ORDERS_NO NUMBER CONSTRAINT POINTS_ORDERS_NO_FK REFERENCES ORDERS(ORDERS_NO),
    REG_DATE DATE CONSTRAINT POINTS_REG_DATE_NN NOT NULL,
    POINT NUMBER DEFAULT 0,
    HISTORY VARCHAR2(20) CONSTRAINT POINTS_HISTORY_NN NOT NULL
);

COMMENT ON COLUMN POINTS.ORDERS_NO IS '주문번호';
COMMENT ON COLUMN POINTS.REG_DATE IS '등록일자';
COMMENT ON COLUMN POINTS.POINT IS '포인트';
COMMENT ON COLUMN POINTS.HISTORY IS '적립내역';
